package src;

public class SeedPoint {
    private Node node;// 坐标属性
    private int x;
    private int y;
    private final boolean autoGenerated;

    public SeedPoint(Node node) {
        this.node = node;
        x = node.x;
        y = node.y;
        autoGenerated = false;
    }

    public SeedPoint(int x, int y) {
        this.x = x;
        this.y = y;
        this.node = new Node(x,y);
        autoGenerated = false;
    }

    public SeedPoint(int x, int y, boolean autoGenerated) {
        this.x = x;
        this.y = y;
        this.node = new Node(x,y);
        this.autoGenerated = autoGenerated;
    }

    public Node getNode() {
        return node;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }


    // 梯度属性
    // ......
}
